on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Merge Release Branch']
    types:
      - completed

name: Generate Documentation

jobs:
  render:
    name: Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install xetex
        run: |
          sudo apt-get install texlive-xetex
          sudo apt install librsvg2-bin
          sudo apt install 'fonts-dejavu*'

      - name: Setup Env
        id: setup
        env:
          PREFIX: AWS-SEA
          SUFFIX: Documentation
        run: |
          mkdir ${PREFIX}-${SUFFIX}
          echo ::set-output name=prefix::$(echo "${PREFIX}")
          echo ::set-output name=suffix::$(echo "${SUFFIX}")
          echo ::set-output name=dir::$(echo "${PREFIX}-${SUFFIX}")

      - name: PDF output 0
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/0-${{ steps.setup.outputs.prefix }}-Solution-Summary.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=8.5in
            -V geometry:paperheight=11in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            README.md

      - name: PDF output 1
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/1-${{ steps.setup.outputs.prefix }}-Installation-Guide.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=8.5in
            -V geometry:paperheight=11in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            docs/installation/installation.md

      - name: PDF output 2
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/2-${{ steps.setup.outputs.prefix }}-Ops-FAQ.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=8.5in
            -V geometry:paperheight=11in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            docs/faq/faq.md

      - name: Copy file output 3
        run: |
          cp docs/architectures/AWS_Diagrams_Account_Network_VPC.pdf ${{ steps.setup.outputs.dir }}/3-${{ steps.setup.outputs.prefix }}-Diagrams_Account_Network_VPC.pdf

      - name: PDF output 4a
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/4a-${{ steps.setup.outputs.prefix }}-Config-File-Customization.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=8.5in
            -V geometry:paperheight=11in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            docs/installation/customization-index.md

      - name: Copy file output 4b
        run: |
          cp reference-artifacts/SAMPLE_CONFIGS/config.example.json ${{ steps.setup.outputs.dir }}/4b-${{ steps.setup.outputs.prefix }}-config.example.json

      - name: Copy file output 4b1
        run: |
          cp reference-artifacts/SAMPLE_CONFIGS/config.lite-VPN-example.json ${{ steps.setup.outputs.dir }}/4b-${{ steps.setup.outputs.prefix }}-config.lite-VPN-example.json

      - name: Copy file output 4b2
        run: |
          cp reference-artifacts/SAMPLE_CONFIGS/config.multi-region-example.json ${{ steps.setup.outputs.dir }}/4b-${{ steps.setup.outputs.prefix }}-config.multi-region-example.json

      - name: Copy file output 4b3
        run: |
          cp reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json ${{ steps.setup.outputs.dir }}/4b-${{ steps.setup.outputs.prefix }}-config.ultralite-example.json

      - name: PDF output 4c
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/4c-${{ steps.setup.outputs.prefix }}-Multi-file-Config-Capabilities.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=8.5in
            -V geometry:paperheight=11in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            docs/installation/multi-file-config-capabilities.md

      - name: PDF output 4d
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/4d-${{ steps.setup.outputs.prefix }}-Config-Sample-Snippets.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=8.5in
            -V geometry:paperheight=11in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            ./reference-artifacts/SAMPLE_CONFIGS/sample_snippets.md

      - name: Copy file output 4e
        run: |
          cp reference-artifacts/Third-Party/firewall-example-A-A-singletunnel.txt ${{ steps.setup.outputs.dir }}/4e-${{ steps.setup.outputs.prefix }}-firewall-example-A-A-singletunnel.txt

      - name: Copy file output 4e1
        run: |
          cp reference-artifacts/Third-Party/firewall-example-A-A-multitunnel.txt ${{ steps.setup.outputs.dir }}/4e-${{ steps.setup.outputs.prefix }}-firewall-example-A-A-multitunnel.txt

      - name: PDF output 4f
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/4f-${{ steps.setup.outputs.prefix }}-Firewall-config-Customizations.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=8.5in
            -V geometry:paperheight=11in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            ./reference-artifacts/SAMPLE_CONFIGS/firewall_file_available_variables.md

      - name: PDF output 4g
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/4g-${{ steps.setup.outputs.prefix }}-logging-locations.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=11in
            -V geometry:paperheight=8.5in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            docs/architectures/pbmm/log-file-locations.md

      - name: PDF output 4h
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/4h-${{ steps.setup.outputs.prefix }}-What-Where.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=11in
            -V geometry:paperheight=8.5in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            docs/installation/what-we-do-where.md

      - name: PDF output 4i
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/4i-${{ steps.setup.outputs.prefix }}-Public-Workload-Fortigate.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=8.5in
            -V geometry:paperheight=11in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            docs/installation/guides/public-facing-workload-via-fortigate.md

      - name: PDF output 5
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/5-${{ steps.setup.outputs.prefix }}-Operations-Troubleshooting-Guide.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=8.5in
            -V geometry:paperheight=11in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            docs/operations/operations-troubleshooting-guide.md

      - name: PDF output 6
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/6-${{ steps.setup.outputs.prefix }}-Developer-Guide.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=8.5in
            -V geometry:paperheight=11in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            docs/developer/developer-guide.md

      - name: PDF output 7
        uses: docker://pandoc/latex:2.10
        with:
          args: >
            --output=${{ steps.setup.outputs.dir }}/7-${{ steps.setup.outputs.prefix }}-PBMM-Architecture.pdf
            --from=gfm
            --resource-path=.:docs/architectures/pbmm:docs/installation:docs/operations
            -V linkcolor:blue
            -V geometry:paperwidth=8.5in
            -V geometry:paperheight=11in
            -V geometry:margin=.8in
            -V documentclass=report
            --pdf-engine=xelatex
            docs/architectures/pbmm/architecture.md

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.dir }}
          path: ${{ steps.setup.outputs.dir }}/
